### PR TITLE
Enhance Travis config

### PR DESCRIPTION
**Pull request by szepeviktor**
Please see the diff.

### CODE REVIEW

**Comment by gmazzap** [comment]
Thanks @szepeviktor 

I'm probably going to phase out Travis and move to GitHub action so I have less SAAS to deal with.

Just curious, why `composer validate` before `composer install`?

`composer install` executes validation anyway, so checking for validation equals to (pseudo-code):

```
if ( composer_validate() ) {
  if (  composer_validate() ) {
     composer_do_install()
  }
}
```

**Comment by szepeviktor** [comment]
> Just curious, why `composer validate` before `composer install`?

`composer install` will happily overlook Composer schema violations, e.g. missing license.

**Comment by gmazzap** [comment]
There's nothing in the _schema_ that forces license, see https://getcomposer.org/schema.json

Actually, what `composer install` does is _exactly_ validating the schema, this is why a missing license does not stop it.

Missing license is a _suggestion_ from Composer, something that I'm happy to skip in a CI that runs unit tests.

**Comment by szepeviktor** [comment]
All right. If warnings are fine then this PR (and me) has no use 😿 

kép

**Pull request closed without merging**
